### ISSUE TITLE
Fab menu has too much click area when closed

### ISSUE THREAD

**Issue by wuxiaoying** [cwdoh/paper-fab-menu#13]
When the menu is in the open state, it takes up the items + fab button's area. This is fine, because the user expects that clicking on them registers to the fab menu element. However, when the menu is closed (with only the fab button showing), the area still covers the items. Trying to click on an element behind it registers on the fab menu instead, which is counter intuitive because there's nothing there.

**Comment by cwdoh** [comment]
You're right. I totally forgot this issue! Thanks for filing! :)

**Comment by cwdoh** [comment]
Just have committed some code for moving every paper-fab-menu-item away when closed. I think this is just a quick solution to fix this issue, but it works well for me. Please check your issue is also cleared, @wuxiaoying. :)

**Comment by cwdoh** [comment]
Oops, didn't fix. Need to reconstruct DOM tree of submenu container. :/

**Comment by cwdoh** [comment]
Fixed. :)
