### ISSUE TITLE
Core-overlay issue when used within paper-dialog

### ISSUE THREAD

**Issue by mrtedgeesq** [cwdoh/paper-fab-menu#4]
Hi there, 
Excellent work, but I've found an issue when this is used within a paper-dialog which has the 'backdrop' tag.

Symptoms:
1. The core-overlay that should be triggered when the menu is shown appears behind the paper-dialog instead of between the paper-dialog and the paper-fab-menu
2. When the paper-dialog is closed, one of the core-overlay-layers retains the class "core-opened". This means that a transparent overlay stays open above the rest of the ui, so that the user can't interact with any components! I don't know whether the one that is left open is from the dialog backdrop or the paper-fab-menu

I'm trying to find a fix/workaround for this but so far I haven't been able to

**Comment by cwdoh** [comment]
I wrote quick workaround code, and it works. However, I can't it would be the right solution for solving this issue. Anyway if you want to test it, check 16558348ecc4d3091328f5b4e55ca505f2476f4a. You can test it via demo-with-dialog.html. Thanks. :)

**Comment by cwdoh** [comment]
Merged at [v0.0.2](https://github.com/cwdoh/paper-fab-menu/tree/v0.0.2).
