### ISSUE TITLE
Add optional overlay

### ISSUE THREAD

**Issue by zdarovka** [cwdoh/paper-fab-menu#8]
It would be nice if there was an option to use / not use overlay with menu.

**Comment by zdarovka** [comment]
I created pr #7  with working solution. But the way I did it does not seem nice, maybe you have a better solution.

**Comment by cwdoh** [comment]
I'll check your code soon. Thanks @zdarovka for filing. :)

**Comment by cwdoh** [comment]
Merged at #9
